version: "2.2"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
        container_name: elasticsearch
        ports:
            - "9200:9200"
        networks:
            - elasticsearch-dev-network
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
    kibana:
        image: docker.elastic.co/kibana/kibana:8.11.1
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on: 
            - elasticsearch
        networks:
            - elasticsearch-dev-network
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
    elasticsearch-dev-network:
        driver: bridge
